version: '3.8'

services:
  django:
    build:
      context: ./assets_monitor
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./assets_monitor/.env
    volumes:
      - ./assets_monitor:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build:
      context: ./assets_monitor
    command: celery -A assets_monitor worker --loglevel=info
    volumes:
      - ./assets_monitor:/app
    depends_on:
      - redis

  celery_beat:
    build:
      context: ./assets_monitor
    command: celery -A assets_monitor beat -l info
    volumes:
      - ./assets_monitor:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - django
