version: '3.8'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A assets_monitor worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_beat:
    build: .
    command: celery -A assets_monitor beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
